### ISSUE TITLE
What you mean broken types

### ISSUE THREAD

**Issue by Murasame233** [datdenkikniet/github-runner-proxmox-manager#11]
I think you are already fix it.
`broken.md` under `generate` crate

**Comment by Murasame233** [comment]
And the dump schema should be running under Proxmox host. Can we store schema.json in repo?

**Comment by datdenkikniet** [comment]
Included a version of the schema in the source tree now, albeit xz compressed because the original file is 3.2MB. 

CI still creates an original from proxmox-ve sources, so it will detect differences that we do not account for.

`BROKEN.md` should cover the missing bits :) I have finally signed the CLA and plan on addressing the broken things found so far.
